FROM amazonlinux:2

RUN yum -y update \
  && yum -y install java-17-amazon-corretto-devel awscli unzip \
  && yum clean all \
  && rm -rf /var/cache/yum

RUN JVM_PATH=/usr/lib/jvm/java-17-amazon-corretto.x86_64

ENV JAVA_HOME /usr/lib/jvm/java-17-amazon-corretto.x86_64
